/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dell
 */
import Logic.PersonParentClass;
import Logic.PersonDirectory;
import Logic.PatientDirectory;
import Logic.VitalSignsPatient;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class MainAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainAppFrame
     */
    PersonDirectory persons;
    PatientDirectory patients;
    VitalSignsPatient vitalSignsHistory;
    
    public MainAppFrame() throws IOException{
        initComponents();
        this.persons = new PersonDirectory();
        this.patients = new PatientDirectory();
        this.vitalSignsHistory = new VitalSignsPatient(); 
        
        PersonParentClass p = persons.addNewPerson();
        p.setPersonName("John");
        p.setPersonAge(26);
        p.setPersonCity("Boston");
        p.setPersonCommunity("Mission Main");
        p.setPersonHouse("8C");
        p.setPersonMedRecNo(1);
        
        p = persons.addNewPerson();
        p.setPersonName("Andie");
        p.setPersonAge(25);
        p.setPersonCity("Boston");
        p.setPersonCommunity("Roxbury");
        p.setPersonHouse("6C");
        p.setPersonMedRecNo(2);
        
        p = persons.addNewPerson();
        p.setPersonName("Garry");
        p.setPersonAge(12);
        p.setPersonCity("New York");
        p.setPersonCommunity("Brooklyn");
        p.setPersonHouse("1575");
        p.setPersonMedRecNo(3);
        
        p = persons.addNewPerson();
        p.setPersonName("Vini");
        p.setPersonAge(16);
        p.setPersonCity("NewYork");
        p.setPersonCommunity("Brooklyn");
        p.setPersonHouse("19C");
        p.setPersonMedRecNo(4);
        
        p = persons.addNewPerson();
        p.setPersonName("Shivani");
        p.setPersonAge(50);
        p.setPersonCity("Texas");
        p.setPersonCommunity("Mission Main");
        p.setPersonHouse("5C");
        p.setPersonMedRecNo(5);
        
        p = persons.addNewPerson();
        p.setPersonName("Venu");
        p.setPersonAge(55);
        p.setPersonCity("Boston");
        p.setPersonCommunity("Roxbury");
        p.setPersonHouse("50C");
        p.setPersonMedRecNo(6);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnViewPerson = new javax.swing.JButton();
        btnViewPatients = new javax.swing.JButton();
        btnAddPerson = new javax.swing.JButton();
        btnPatientHistory = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnViewPerson.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewPerson.setText("Manage Persons");
        btnViewPerson.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnViewPatients.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewPatients.setText("Manage Patients");
        btnViewPatients.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientsActionPerformed(evt);
            }
        });

        btnAddPerson.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddPerson.setText("Create Person");
        btnAddPerson.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        btnPatientHistory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPatientHistory.setText("View Patient History");
        btnPatientHistory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPatientHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(693, 598));
        jPanel2.setPreferredSize(new java.awt.Dimension(693, 598));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\medical-record.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        CreatePersonDetails createJPanel = new CreatePersonDetails(persons);
        jSplitPane1.setRightComponent(createJPanel);        
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
        ManagePersonPanel displayPersonJPanel = new ManagePersonPanel(persons, patients, vitalSignsHistory);
        jSplitPane1.setRightComponent(displayPersonJPanel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed
        // TODO add your handling code here:
        ManagePatientsPanel displayPatientJPanel = new ManagePatientsPanel(patients, vitalSignsHistory);
        jSplitPane1.setRightComponent(displayPatientJPanel);
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        // TODO add your handling code here:
        ViewHistory historyRecordPanel = new ViewHistory(vitalSignsHistory);
        jSplitPane1.setRightComponent(historyRecordPanel);
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainAppFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainAppFrame.class.getName()).log(Level.SEVERE, null,ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
