/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.FoodItems.FoodItem;

import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainerSAWAP;
    EcoSystem ecosystemSAWAP;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainerSAWAP = userProcessContainer;
        this.ecosystemSAWAP = ecosystem;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel modelSAWAP=(DefaultTreeModel)jTreeSAWAP.getModel();
       // Add the code for draw your system structure shown by JTree
        //MutableTreeNode root = (MutableTreeNode) model.getRoot();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)modelSAWAP.getRoot();
        root.removeAllChildren();
        DefaultMutableTreeNode es = new DefaultMutableTreeNode("Ecosystem");
        root.add(es);
        DefaultMutableTreeNode cd = new DefaultMutableTreeNode("Customer Directory");
        es.add(cd);
        for(Customer c : ecosystemSAWAP.getCustomerDirectory().getCustomerList())
        {
            DefaultMutableTreeNode cu = (DefaultMutableTreeNode)es.getRoot();
            cd.add(new DefaultMutableTreeNode(c.getName()));
        }
        DefaultMutableTreeNode rd = new DefaultMutableTreeNode("Restaurant Directory");
        es.add(rd);
        
        for(Restaurant r : ecosystemSAWAP.getRestaurantDirectory().getRestaurantList())
        {
            //DefaultMutableTreeNode cu = (DefaultMutableTreeNode)rd.getRoot();
            DefaultMutableTreeNode sd = new DefaultMutableTreeNode(r.getName());
            rd.add(sd);
            DefaultMutableTreeNode ed = new DefaultMutableTreeNode("Employee Directory");
            sd.add(ed);
            DefaultMutableTreeNode manager = new DefaultMutableTreeNode("Manager Directory");
            ed.add(manager);
            DefaultMutableTreeNode deliver = new DefaultMutableTreeNode("Delivery Man Directory");
            ed.add(deliver);
            for(Employee e : r.getEmployeeDirectory().getEmployeeList())
            {
                for(UserAccount u : ecosystemSAWAP.getUserAccountDirectory().getUserAccountList())
                {
                    if(u.getEmployee().equals(e))
                    {
                        if(u.getRole().toString() == "Business.Role.AdminRole")
                        {
                            DefaultMutableTreeNode ar = new DefaultMutableTreeNode(e.getName());
                            manager.add(ar);
                        }
                        else if(u.getRole().toString() == "Business.Role.DeliverManRole")
                        {
                            DefaultMutableTreeNode dm = new DefaultMutableTreeNode(e.getName());
                            deliver.add(dm);
                        }
                    }
                }
            }
            
            //DefaultMutableTreeNode fl = (DefaultMutableTreeNode)rd.getRoot();
            DefaultMutableTreeNode f = new DefaultMutableTreeNode("Menu");
            sd.add(f);
            for(FoodItem fi : r.getMenu().getFoodItemList())
            {
                DefaultMutableTreeNode z = (DefaultMutableTreeNode)ed.getRoot();
                f.add(new DefaultMutableTreeNode(fi.getName()));
            }
        }
        
        modelSAWAP.reload(root);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeSAWAP = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();
        btnManageCustomersSAWAP = new javax.swing.JButton();
        btnManageRestaurantsSAWAP = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeSAWAP.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeSAWAP.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeSAWAPValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeSAWAP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Admin Panel");

        jLabel1.setText("Selected Node:");

        lblSelectedNode.setText("<View_selected_node>");

        btnManageCustomersSAWAP.setBackground(new java.awt.Color(255, 255, 255));
        btnManageCustomersSAWAP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnManageCustomersSAWAP.setForeground(new java.awt.Color(0, 102, 102));
        btnManageCustomersSAWAP.setText("Manage Customers");
        btnManageCustomersSAWAP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCustomersSAWAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersSAWAPActionPerformed(evt);
            }
        });

        btnManageRestaurantsSAWAP.setBackground(new java.awt.Color(255, 255, 255));
        btnManageRestaurantsSAWAP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnManageRestaurantsSAWAP.setForeground(new java.awt.Color(0, 102, 102));
        btnManageRestaurantsSAWAP.setText("Manage restaurants");
        btnManageRestaurantsSAWAP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageRestaurantsSAWAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRestaurantsSAWAPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnManageCustomersSAWAP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectedNode)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRestaurantsSAWAP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageCustomersSAWAP, btnManageRestaurantsSAWAP});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelectedNode)
                .addGap(43, 43, 43)
                .addComponent(btnManageCustomersSAWAP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageRestaurantsSAWAP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageCustomersSAWAP, btnManageRestaurantsSAWAP});

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeSAWAPValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeSAWAPValueChanged

        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)jTreeSAWAP.getLastSelectedPathComponent();
        if(selectedNode!=null){
            lblSelectedNode.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_jTreeSAWAPValueChanged

    private void btnManageCustomersSAWAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersSAWAPActionPerformed
        SystemAdminManageCustomers uc = new SystemAdminManageCustomers(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserCustomer", uc);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
    }//GEN-LAST:event_btnManageCustomersSAWAPActionPerformed

    private void btnManageRestaurantsSAWAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRestaurantsSAWAPActionPerformed
        SystemAdminManageRestaurant um = new SystemAdminManageRestaurant(userProcessContainerSAWAP, ecosystemSAWAP);
        userProcessContainerSAWAP.add("UserManager", um);
        CardLayout layout = (CardLayout)this.userProcessContainerSAWAP.getLayout();
        layout.next(userProcessContainerSAWAP);
    }//GEN-LAST:event_btnManageRestaurantsSAWAPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCustomersSAWAP;
    private javax.swing.JButton btnManageRestaurantsSAWAP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTreeSAWAP;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
