/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import cprofile.ClassProfile;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;

/**
 *
 * @author Dell
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    boolean nameFlagSC;
    boolean addFlagSC;
    boolean dobFlagSC;
    boolean mailFlagSC;
    boolean telFlagSC;
    boolean SSNFlagSC;
    
    ClassProfile CP;
    
    public CreateJPanel(ClassProfile CP) {
        initComponents();
        this.CP = CP; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblTelNo = new javax.swing.JLabel();
        lblFaxNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedRecNo = new javax.swing.JLabel();
        lblHealthBenNo = new javax.swing.JLabel();
        lblBankAcc = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblVehNo = new javax.swing.JLabel();
        lblDevNo = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtNameCP = new javax.swing.JTextField();
        txtAddressCP = new javax.swing.JTextField();
        txtTelNoCP = new javax.swing.JTextField();
        txtFaxNoCP = new javax.swing.JTextField();
        txtEmailCP = new javax.swing.JTextField();
        txtSSNCP = new javax.swing.JTextField();
        txtMedRecNoCP = new javax.swing.JTextField();
        txtHBenNoCP = new javax.swing.JTextField();
        txtBankAccCP = new javax.swing.JTextField();
        txtLicenseNoCP = new javax.swing.JTextField();
        txtVehNoCP = new javax.swing.JTextField();
        txtDevNoCP = new javax.swing.JTextField();
        txtLinkedinCP = new javax.swing.JTextField();
        txtIPCP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnphotouploadCP = new javax.swing.JButton();
        lblChoosePhotoToUpload = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNameErr = new javax.swing.JLabel();
        dateChooserCP = new com.toedter.calendar.JDateChooser();
        lblAddErr = new javax.swing.JLabel();
        lblTelErr = new javax.swing.JLabel();
        lblEmailErr = new javax.swing.JLabel();
        lblDateErr = new javax.swing.JLabel();
        lblSSNErr = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblBAerr = new javax.swing.JLabel();
        lblVehErr = new javax.swing.JLabel();
        lblFaxErr = new javax.swing.JLabel();
        lblLicErr = new javax.swing.JLabel();
        lblDeviceErr = new javax.swing.JLabel();
        lblHelErr = new javax.swing.JLabel();
        lblMedErr = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 640));
        setMinimumSize(new java.awt.Dimension(800, 640));
        setPreferredSize(new java.awt.Dimension(800, 640));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Class Profile");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("Name:");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAddress.setText("Address:");

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDOB.setText("DOB:");

        lblTelNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelNo.setText("Tel. No:");

        lblFaxNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFaxNo.setText("Fax. No");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setText("Email:");

        lblSSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSSN.setText("SSN");

        lblMedRecNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMedRecNo.setText("Med. rec. no.:");

        lblHealthBenNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHealthBenNo.setText("HBen. no.");

        lblBankAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBankAcc.setText("Bank Acc no.:");

        lblLicense.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLicense.setText("License no:");

        lblVehNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVehNo.setText("Veh. no:");

        lblDevNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDevNo.setText("Dev no.");

        lblLinkedin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLinkedin.setText("LinkedIn:");

        lblIPAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIPAddress.setText("IP address");

        lblPhoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPhoto.setText("Photo upload");

        txtNameCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCPActionPerformed(evt);
            }
        });

        txtTelNoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNoCPActionPerformed(evt);
            }
        });

        txtFaxNoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNoCPActionPerformed(evt);
            }
        });

        txtEmailCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCPActionPerformed(evt);
            }
        });

        txtMedRecNoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedRecNoCPActionPerformed(evt);
            }
        });

        txtHBenNoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHBenNoCPActionPerformed(evt);
            }
        });

        txtBankAccCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankAccCPKeyReleased(evt);
            }
        });

        txtIPCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPCPActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnphotouploadCP.setText("Attach");
        btnphotouploadCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotouploadCPActionPerformed(evt);
            }
        });

        lblChoosePhotoToUpload.setText("Click to upload photo");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("eg. Sherlock ");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("eg. 235 Bolyston Street");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("eg. 6176029698");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("blah@gmail.com");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("eg. 123456789123");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("eg. 123456");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("eg. 123456");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("eg. 1234567890");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("eg: 856-45-6789");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("eg. 123456");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("eg. 192.167.12.46");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("eg. 123456");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("eg. 123456");

        lblNameErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblNameErr.setForeground(new java.awt.Color(255, 51, 0));

        lblAddErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblAddErr.setForeground(new java.awt.Color(255, 51, 0));

        lblTelErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblTelErr.setForeground(new java.awt.Color(255, 51, 0));

        lblEmailErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblEmailErr.setForeground(new java.awt.Color(255, 51, 0));

        lblDateErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblDateErr.setForeground(new java.awt.Color(255, 51, 0));

        lblSSNErr.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setText("*");

        jLabel16.setForeground(new java.awt.Color(255, 51, 102));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(255, 51, 102));
        jLabel17.setText("*");

        jLabel18.setForeground(new java.awt.Color(255, 51, 102));
        jLabel18.setText("*");

        jLabel19.setForeground(new java.awt.Color(255, 51, 102));
        jLabel19.setText("*");

        jLabel20.setForeground(new java.awt.Color(255, 51, 102));
        jLabel20.setText("*");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("eg. 10-Sep-2021");

        lblBAerr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblBAerr.setForeground(new java.awt.Color(255, 51, 0));

        lblVehErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblVehErr.setForeground(new java.awt.Color(255, 51, 0));

        lblFaxErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblFaxErr.setForeground(new java.awt.Color(255, 51, 0));

        lblLicErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblLicErr.setForeground(new java.awt.Color(255, 51, 0));

        lblDeviceErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblDeviceErr.setForeground(new java.awt.Color(255, 51, 0));

        lblHelErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblHelErr.setForeground(new java.awt.Color(255, 51, 0));

        lblMedErr.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblMedErr.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLinkedin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBankAcc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTelNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBankAccCP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblBAerr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmailCP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSNCP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSSNErr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLinkedinCP, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                .addComponent(txtVehNoCP))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVehErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSSN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblVehNo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDOB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblAddress)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel2)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel1)
                                                                .addComponent(txtNameCP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(txtAddressCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(30, 30, 30)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblNameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblAddErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel4)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtTelNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(39, 39, 39)
                                                    .addComponent(lblTelErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(dateChooserCP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoto)
                            .addComponent(lblHealthBenNo)
                            .addComponent(lblIPAddress))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLicense)
                                .addComponent(lblFaxNo))
                            .addGap(4, 4, 4)))
                    .addComponent(lblMedRecNo)
                    .addComponent(lblDevNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHBenNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnphotouploadCP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChoosePhotoToUpload))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFaxNoCP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtLicenseNoCP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDevNoCP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIPCP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addComponent(txtMedRecNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaxErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDeviceErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHelErr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAddErr, lblDateErr, lblNameErr});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(jLabel9))
                    .addComponent(lblNameErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoto)
                        .addComponent(btnphotouploadCP)
                        .addComponent(lblChoosePhotoToUpload)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtAddressCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAddress)
                                        .addComponent(jLabel16))
                                    .addComponent(lblAddErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMedErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblMedRecNo)
                                            .addComponent(txtMedRecNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDOB)
                                .addComponent(jLabel17))
                            .addComponent(dateChooserCP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHealthBenNo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHBenNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHelErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTelNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelNo)
                                .addComponent(jLabel18))
                            .addComponent(lblTelErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEmailCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEmail)
                                        .addComponent(jLabel19)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIPCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblIPAddress))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblEmailErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeviceErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDevNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDevNo, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)
                                    .addGap(7, 7, 7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBAerr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblBankAcc)
                                            .addComponent(txtBankAccCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicense)
                            .addComponent(txtLicenseNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN)
                            .addComponent(jLabel20)
                            .addComponent(txtSSNCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSNErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVehNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFaxNo)
                                        .addComponent(txtFaxNoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFaxErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(jLabel8)))
                    .addComponent(lblVehErr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinkedinCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedin))
                .addGap(9, 9, 9)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAddressCP, txtNameCP});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmailCP, txtTelNoCP});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBankAccCP, txtSSNCP});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAddErr, lblDateErr, lblNameErr});

    }// </editor-fold>//GEN-END:initComponents

    private void txtNameCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCPActionPerformed

    private void txtEmailCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCPActionPerformed

    private void txtMedRecNoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedRecNoCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedRecNoCPActionPerformed

    private void txtFaxNoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNoCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNoCPActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

//Checks whether any field is empty        
        if(     txtNameCP.getText().isEmpty() || 
                txtAddressCP.getText().isEmpty() || 
                (dateChooserCP == null) ||
                txtTelNoCP.getText().isEmpty() || 
                txtEmailCP.getText().isEmpty() || 
                txtSSNCP.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please complete mandatory fields!");
        }
        else 
            {
               if(txtLinkedinCP.getText().isEmpty() != true)
               {
                   CP.setLinkedin(txtLinkedinCP.getText());
               }  
               
               if(txtIPCP.getText().isEmpty() != true)
               {
                   CP.setIPadd(txtIPCP.getText()); 
               }
               
//Name Validation
            if(nameValidate(txtNameCP.getText()))
            {
                nameFlagSC = true;
                CP.setName(txtNameCP.getText());
                lblNameErr.setText(" ");
            }
            else
            {
                lblNameErr.setText("Invalid Name!");
            }
            
//Address Validation
            if(addressValidate(txtAddressCP.getText()))
            {
                addFlagSC = true;
                CP.setGeodata(txtAddressCP.getText());
                lblAddErr.setText(" ");
            }
            else
            {
                lblAddErr.setText("Invalid Address!");
            }
//Date Validation
            if(dateChooserCP.getDate()!= null)
            {
                dobFlagSC = true; 
                CP.setBirthdate(dateChooserCP.getDate());
                lblDateErr.setText(" ");
            }
            
            else
            {
                lblDateErr.setText("Choose Date");
            }
            
//MobileNumber Validation
            if(mobValidate(txtTelNoCP.getText()))
            {
                telFlagSC = true;
                CP.setTelnum(Long.parseLong(txtTelNoCP.getText()));
                lblTelErr.setText(" ");
            }
            else
            {
                lblTelErr.setText("Invalid Mob. No.!");
            }
            
//Email Validation
            if(emailValidate(txtEmailCP.getText()))
            {
                mailFlagSC = true;
                CP.setEmail(txtEmailCP.getText());
                lblEmailErr.setText(" ");
            }
            
            else
            {
                lblEmailErr.setText("Invalid Email!");
            }

//SSN Validate
            if(ssnValidate(txtSSNCP.getText()))
            { 
              SSNFlagSC = true;
                CP.setSsn(txtSSNCP.getText());
                lblSSNErr.setText(" ");
            }            
            
            else
            {
                lblSSNErr.setText("Invalid SSN!");
            }            
            
//Bank Account field Validation
            if(txtBankAccCP.getText().isEmpty()!= true)
            {
                if(numValidation(txtBankAccCP.getText()))
            {   
                CP.setBankaccnum((Integer.parseInt(txtBankAccCP.getText())));
                lblBAerr.setText(" ");
            }
            
            else
            {
                lblBAerr.setText("Enter digits only");
            }                
            }

            
//Vehicle number validation 
            if(txtVehNoCP.getText().isEmpty() != true)
            {
                if(numValidation(txtVehNoCP.getText()))
            {
                CP.setVehserialnum(Integer.parseInt(txtVehNoCP.getText()));
                lblVehErr.setText(" ");
            }
            
            else
            {
                lblVehErr.setText("Enter digits only");
            }                
            }
            
//Medical number validation    
            if(txtMedRecNoCP.getText().isEmpty() != true)
            {
                if(numValidation(txtMedRecNoCP.getText()))
            {
                CP.setMedrecnum(Integer.parseInt(txtMedRecNoCP.getText()));
                lblMedErr.setText(" ");
            }
            
            else
            {
                lblMedErr.setText("Enter digits only");
            }                
            }
            
//HealthBenNo validation
            if(txtHBenNoCP.getText().isEmpty() != true)
            {
                if(numValidation(txtHBenNoCP.getText()))
            {
                CP.setHelplan(Integer.parseInt(txtHBenNoCP.getText()));
                lblHelErr.setText(" ");
            }
            
            else
            {
                lblHelErr.setText("Enter digits only");
            }                
            }
 
//Device number validation 
            if(txtDevNoCP.getText().isEmpty() != true)
            {
                if(numValidation(txtDevNoCP.getText()))
            {
                CP.setDevserialnum(Integer.parseInt(txtDevNoCP.getText()));
                lblDeviceErr.setText(" ");
            }
            
            else
            {
                lblDeviceErr.setText("Enter digits only");
            }                
            }
            
//License number validation 
            if(txtLicenseNoCP.getText().isEmpty() != true)
            {
                if(numValidation(txtLicenseNoCP.getText()))
            {
                CP.setLicensenum(Integer.parseInt(txtLicenseNoCP.getText()));
                lblLicErr.setText(" ");
            }
            
            else
            {
                lblLicErr.setText("Enter digits only");
            }                
            }
            
//Fax number validation
            if(txtFaxNoCP.getText().isEmpty() != true)
            {
                if(numValidation(txtFaxNoCP.getText()))
            {
                CP.setFax(Integer.parseInt(txtFaxNoCP.getText()));
                lblFaxErr.setText(" ");
            }
            
            else
            {
                lblFaxErr.setText("Enter digits only");
            }                
            }
            
//Will set fields only if mandatory fields validation is successful            
            if(nameFlagSC == true &&
               addFlagSC == true && 
               telFlagSC == true && 
               dobFlagSC == true && 
               SSNFlagSC == true && 
               mailFlagSC == true)
            {
//               CP.setName(txtName.getText());
//               CP.setGeodata(txtAddress.getText());
//               CP.setBirthdate(dateChooser.getDate());
//               CP.setTelnum(Long.parseLong(txtTelNo.getText()));
//               CP.setEmail(txtEmail.getText());
//               CP.setSsn(txtSSN.getText());               
//               CP.setLinkedin(txtLinkedin.getText());               
//               CP.setIPadd(txtIP.getText());
               JOptionPane.showMessageDialog(this,"Profile Created Successfully!");
            }
         }         

             
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnphotouploadCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotouploadCPActionPerformed
        // TODO add your handling code here:
        int pic;
        JFileChooser uploadphoto = new JFileChooser();
        pic = uploadphoto.showSaveDialog(null);
        if (pic == JFileChooser.APPROVE_OPTION)
        {
            File currentPhoto = uploadphoto.getSelectedFile();
            CP.setImage(currentPhoto);
        }        
    }//GEN-LAST:event_btnphotouploadCPActionPerformed

    private void txtBankAccCPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccCPKeyReleased

    }//GEN-LAST:event_txtBankAccCPKeyReleased

    private void txtTelNoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNoCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNoCPActionPerformed

    private void txtIPCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPCPActionPerformed

    private void txtHBenNoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHBenNoCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHBenNoCPActionPerformed

    private boolean ssnValidate(String ssn_val) {
        
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        String regex = "^(?!666|000|9\\d{2})\\d{3}"
                       + "-(?!00)\\d{2}-"
                       +"(?!0{4})\\d{4}$";
        
        Pattern p = Pattern.compile(regex);
        
        if (ssn_val == null)
        {
            return false;
        }
        
        Matcher m = p.matcher(ssn_val);
        return m.matches();
        
    }

    private boolean mobValidate(String mobnum) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Pattern p = Pattern.compile("^\\d{10}$");
        
        if(mobnum == null)
        {
            return false;
        }
        
        Matcher m = p.matcher(mobnum);
        return (m.matches());   
    }

    private boolean nameValidate(String text) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String regex = "^[A-Za-z]\\w{5,29}$";
        Pattern p = Pattern.compile(regex);
        if (text == null) {
            return false;
        }
        Matcher m = p.matcher(text);
        return m.matches();        
    }

    private boolean addressValidate(String text) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        if(text.length() < 6)
        {
            return false;

        }
        else
        {
            return true;
        }
    }

    private boolean emailValidate(String mailID) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    if(mailID.contains("@") && ((mailID.contains(".co") || (mailID.contains(".edu")))))
    {
        return true;
    }
    
    else
    {
        return false;
    }
    }
    
    private boolean numValidation(String text) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
    Pattern p = Pattern.compile("[0-9]+");
        
    if(text == null)
    {
       return false;
    }
        
        Matcher m = p.matcher(text);
       return (m.matches());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnphotouploadCP;
    private com.toedter.calendar.JDateChooser dateChooserCP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAddErr;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBAerr;
    private javax.swing.JLabel lblBankAcc;
    private javax.swing.JLabel lblChoosePhotoToUpload;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDateErr;
    private javax.swing.JLabel lblDevNo;
    private javax.swing.JLabel lblDeviceErr;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailErr;
    private javax.swing.JLabel lblFaxErr;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblHealthBenNo;
    private javax.swing.JLabel lblHelErr;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblLicErr;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedErr;
    private javax.swing.JLabel lblMedRecNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameErr;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSSNErr;
    private javax.swing.JLabel lblTelErr;
    private javax.swing.JLabel lblTelNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehErr;
    private javax.swing.JLabel lblVehNo;
    private javax.swing.JTextField txtAddressCP;
    private javax.swing.JTextField txtBankAccCP;
    private javax.swing.JTextField txtDevNoCP;
    private javax.swing.JTextField txtEmailCP;
    private javax.swing.JTextField txtFaxNoCP;
    private javax.swing.JTextField txtHBenNoCP;
    private javax.swing.JTextField txtIPCP;
    private javax.swing.JTextField txtLicenseNoCP;
    private javax.swing.JTextField txtLinkedinCP;
    private javax.swing.JTextField txtMedRecNoCP;
    private javax.swing.JTextField txtNameCP;
    private javax.swing.JTextField txtSSNCP;
    private javax.swing.JTextField txtTelNoCP;
    private javax.swing.JTextField txtVehNoCP;
    // End of variables declaration//GEN-END:variables

}
