/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Application.Uber;
import Application.UberInventory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell
 */
public class UpdatedCarEntryTablePanel extends javax.swing.JPanel {
    
    private JPanel rightJPanel;
    private UberInventory uberCatalog;
    private ArrayList<Uber> result;

    /**
     * Creates new form UpdatedTablePanel
     */
    UpdatedCarEntryTablePanel(JPanel rightJPanel, ArrayList<Uber> result) {
        initComponents();
         this.rightJPanel = rightJPanel;
         this.result = result;
         
         populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateRide = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarUpdated = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnBACKfuncU = new javax.swing.JButton();

        setBackground(new java.awt.Color(185, 180, 180));

        lblCreateRide.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCreateRide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateRide.setText("Updated Table ");

        tblCarUpdated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Brand", "Car model", "Manufacturing Year", "Max.number of Seats", "Minimum no.ofBachelors", "Car Serial No.", "City", "Car Availability", "Expired_Data"
            }
        ));
        tblCarUpdated.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblCarUpdated);

        btnView.setText("VIEW");

        btnBACKfuncU.setText("BACK");
        btnBACKfuncU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKfuncUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBACKfuncU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreateRide, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateRide, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBACKfuncU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBACKfuncUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKfuncUActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layoutUpdate = (CardLayout) rightJPanel.getLayout();
        layoutUpdate.previous(rightJPanel);
    }//GEN-LAST:event_btnBACKfuncUActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBACKfuncU;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateRide;
    private javax.swing.JTable tblCarUpdated;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
         //To change body of generated methods, choose Tools | Templates.
         DefaultTableModel dtm = (DefaultTableModel) tblCarUpdated.getModel();
            dtm.setRowCount(0);
            for (Uber uber : result)
            {
                
                Object[] row = new Object [9];
                row [0] = uber;
                row [1] = uber.getCarModelNo();
                row [2] = uber.getCarManuYear();
                row [3] = uber.getCarMaxSeats();
                row [4] = uber.getCarMinSeats();
                row [5] = uber.getCarSerialNo();
                row [6] = uber.getCity();
                row [7] = uber.isCarAvailability();
                row [8] = uber.isCarExpiry();
                
                dtm.addRow(row);
                
            }
    }
}
